# nginx.conf
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    server {
        listen 80;

        # Serve static files from /usr/share/nginx/html
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri /index.html;
        }

        # Redirect /api calls to port 5000
        location /api/ {
            proxy_pass http://172.17.0.1:5000/api/;
        }
    }
}